### ISSUE TITLE
strings.txt?

### ISSUE THREAD

**Issue by zelk696** [krogenth/G2DataGUI#1]
Grandia II Anniversary Edition\content\data\text\
にある「strings.txt」でアイテム欄の変更が可能のようです。

現在は既存のアイテム名しか変更できないようですが、配布されているハードモードMODなどで新たに追加されたアイテムの名前変更もここでできるのでしょうか？

--

Grandia II Anniversary Edition\content\data\text\
It seems that you can change the item name with "strings.txt" in.

Currently it seems that only existing item names can be changed, but is it possible to change the names of newly added items such as the hard mode mods distribute?

**Comment by krogenth** [comment]
申し訳ありませんが、ゲームがさまざまな言語をどのように処理するかを調べたことはありません。 残念ながら、私は現在モデルデータの処理に集中しているため、これをすぐに確認することはできません。 これについては、後で詳しく調べます。
