### ISSUE TITLE
A few questions

### ISSUE THREAD

**Issue by VaylenObscuras** [krogenth/G2DataGUI#12]
Opening up another to clear a few things up. I wonder if I can edit some things - like editing effects of magic, skills or the cost to get a skill - while on a playthrough safely without losing myself. Could basically build a mod as I go and test out stuff. 
Edit: Just saw that you replied to the closed question. By editing as I go, I really meant stuff like corrupting the save/requiring to start a new game. Aside from starting stats, what else would I need to pay attention to? And also.. do you know of a decent save editor? Would likely be pretty helpful to have. I remember doing some small edits to the saves myself via the hexedit, though..

Is it impossible to code water or forest elemental damage? What exactly does something like leafwater chant affect aside from the heals? 
And what is "MDT"? 

And a few questions about some of the editable lines.. 
In MS_Param, what does "Target Effect" do? Is it just for visuals, or does it affect gameplay? 
What exactly does "multiplier" in there do? I assume it's the per level bonus to damage, but I need to know what it exactly affects. 
On the topic of Multipliers, I am a bit confused with skills. I don't exactly know what the multiplier actually does, some numbers seem very off, like for Life Up and the Chants
I assume Element Strength is like.. splitting elemental and non-elemental damage? Any info on that one? 

And lastly, how can I edit stuff like base stats, stat gain on levelup, xp needed for levelup and other character specific stuff? Figured they'd be in PC_INIT, but can't seem to find those. 

Oh, and who is that new character, Ryduo x)?

**Comment by krogenth** [comment]
I'll try and hit everything, so please bear with me if I miss something here:

1. As far as I am aware, this is no `water`/`forest` elemental damage, though there might be values for them, I am unsure, this can be tested.
2. `MDT` is the file extension for the maps(i.e. `Carbo Village`), the drop down should display the name for each map area(some map names are garbage data).
3. `Target Effect` defines what the move actually does(damage, healing, some effect, etc.). The visuals would be the `Animation` value.
4. `Multiplier` is a bit tricky, but my understanding of it is that it is a per-level multiplier for the `Strength` value.
5. Last I remember, the skill `Multiplier` is not actually used for anything, so it can safely be ignored.
6. `Elemental Strength` defines the percentage (times 10) that the move has for that specific elemental type. So for example, a value for `4` here would give a `40%` elemental strength for that element.
7. `Base Stats` are in `PC_INIT`, all the per level-up values are in a different file: `TB_LVUP.BIN`, but it defines all characters and each level, which seemed a bit tedious to work with. I can however add that in the future.
8. `Ryduo` is a spelling mistake, thanks for catching that!

**Comment by krogenth** [comment]
In regards to save editing, I don't believe there exists an easy program to modify saves, no. The best resource currently is the old guide on steam: https://steamcommunity.com/sharedfiles/filedetails/?id=565784557

**Comment by VaylenObscuras** [comment]
Thanks for the reply ^.^ 

So, no actual water/forest element, I see. I mean, could be something down the line to add, together with adding some weaknesses/resists to those elements on enemies.. 

I saw the drop down menu in MDT, but don't quite know what to actually use that for. 

So an 8 in elemental strength would be 80% elemental damage, 20% non-elemental(or physical) damage? 

Base stats are in PC_INIT.. hm.. I think they are labled as "unknown", right? Presumably Unknown #15 to #22, if I had to guess. Shouldnt be too hard to find out which number corresponds to whichever stat. 

I think being able to edit level-up stats would be very helpful. Can you create different level-up stats for each character?  So that, for example, Mareg would have exceptional HP growth compared to Elena. 


Multiplier.. so 25 would, presumably, be a 25% increase to the base power of a skill, not the stat multiplier, correct? Or just a +25 onto it? I wonder how exactly I could test it.. 

And on the multiplier thing in SK_PARAM~ I get the impression that it governs the stat increases of leveling the skill. Well, most skills are either "Special" or a simple 10 per level(and they all have a multiplier of 100), but Life Up is(supposedly) 50-800, "Base HP" on 50 and "Multiplier" on 200..... Ahh, I think i get it. I remembered that Life Up had non-linear growth(50/100/200/400/800). So a multiplier of 200 actually modifies the base value, which causes the exponential increase when it is above 100. 

On the topic of skills, specifically Chants, how does the game know which spells to boost? With the Quakeblast charm, for example, I see nothing that categorizes "Boom" as an explosion-elemental spell past maybe the icon. 
And also, does the Leafwater Chant actually do.. anything? Would take quite a long time until i get to the skillbook to test it. 

And lastly, is there a way to edit - or at least see - what all the effects categorized as "Special" - like Gravity or a lot of the skillbook effects - do? Would be helpful if I could actually edit them of course, but at least seeing them and knowing their exact values is probably enough.

**Comment by krogenth** [comment]
1. for MDT, you can change for example: what items you can pick up, and if you want to read a lot, you can technically adjust enemy groups/positions.
2. That is my understanding, correct.
3. Ah, I see what you mean, you want the `STR`, `VIT`, etc. stats, those would be a part of the `TB_LVUP.BIN` file, sorry.
4. Yes, level up statistics are individual for each character, the file defines it as the amount to increase by along with the experience required.
5. I am not entirely sure off the top of my head honestly, that would need to be tested.
6. I vaguely remember testing the skill multiplier at one point, and realizing that it didn't appear to change anything. My guess is that it just has set default ratios to increment by.
7. My assumption is that the chants would adjust based on the `Icon` value of the spells, since for example, `Meteor Strike` has no `Elemental Strength`, but the chant _does_ affect the move.
8. There is this file, but it covers both move and item effects, I never got around to exhaustively testing, so you just get the numeric value to play with: https://github.com/krogenth/G2DataGUI/blob/master/docs/Special_Effects.txt

**Comment by VaylenObscuras** [comment]
So that's in lvlup, too, I see.. How much work would it be to integrate that one into the program? 
And any idea what all those unknowns in PC_INIT might be? There are quite a lot. 

Hm, I think it shouldnt be too hard to test it once I get into some save editing. Any idea where I might be able to find stuff like damage formulas, IP formulas and whatnot? 

Okay, I can test wether that's the case once I get  skillbook. 

The icon, hm~ Yeah, kind of the only thing that could be it. I wonder if the chants also affect stuff like status % for some of the water/forest moves. There isn't really a clean way to test that for me, I fear. 

I looked at the special effects file. It's a bit incomplete, sadly, though most things can be inferred by cross referencing. Is there any way to actually change the values of those "special" effects? Cause stuff like Full Body Blow should have some kind of value attached to them. 

I wonder.. is it possible to "stack" spell or move effects on top of eachother? Like editing a spell to damage enemies in its area and buff allies at the same time? I remember using such kinds of scripts quite often when modding various games and they can be quite useful. Reminds me of the time I modded Warcraft 3 where I often stacked like 5-6 skills on top of eachother to achieve an ultimately simple effect lol.

**Comment by krogenth** [comment]
1. To just make something, not that hard, but finding a decent implementation might take a bit of thought.
2. There is no real documentation on the damage formula, or the IP calculations. There is some speculation on what should roughly work, but they aren't quite right.
3. The effect of `Full-Body Blow` is in the `Special` value. Again, there's different types of "special" between contexts.
4. As far as I am aware, that is not possible within the game. The closest would be finding a special effect that somehow does what you want, if one exists.

**Comment by krogenth** [comment]
I can certainly try to dig them up again, sure.

**Comment by VaylenObscuras** [comment]
Thanks, that would be very helpful. 
Any idea regarding changing the actual effect of stuff that is categorized as "Special"?

**Comment by VaylenObscuras** [comment]
Do you know wether "Strength" has any effect on heals? I noticed all heals only having(a particulary) "Power".

**Comment by VaylenObscuras** [comment]
Oh, and something that occured to me.. When I edit the enemies, do I edit the hardmode version or the normal mode versions?

**Comment by krogenth** [comment]
1. The program works based on the `Normal` version of the game, adding a way to toggle between versions should be possible as well, but it is a lot of data to load and parse.
2. Anything labeled either `Unknown` or has a `(?)` is something I have no idea what it means, or hasn't really been verified in any capacity.
3. Yes, enemies do not have strength or magic, their moves do.
4. Skill values are integer values, you cannot use floating values like `0.5`.

**Comment by VaylenObscuras** [comment]
Thanks for the answers. 

Hm.. It'd really be much easier to base a mod on the hard version instead of the normal version. Do you think you could get a toggle for that done sometime soon? 
My idea was to mod as I play through the game, makes it much easier to judge enemies and having the hardmode versions is just a far better reference point for me. 

May the "Damage(?)" line in the enemy moves be like their strength or Mag for damage calcs, or have you ruled that out already? 

Okay, if a 0.5 is not possible, I think it's impossible to nerf the chants to below +10% per level. Makes me wonder~ is it possible for a Skill in a skillbook to only have 3 levels instead of 5?

**Comment by krogenth** [comment]
It might not be immediately done, but I will find the time to implement these changes to allow further modding.

You could in theory set the required coins to be too much to reach a level 4 or 5, not sure what the max is.

**Comment by VaylenObscuras** [comment]
That would be great if you could find the time for that. In the meantime, I've got to decide wether to play on hard for a better difficulty curve but no ability to mod enemies, or on normal for a worse difficulty curve, but the ability to edit enemies on the fly.. 

Yeah, limiting them via big coin costs to lvl 3 is what I am currently doing. Playing for myself, I can just choose not to use some of the more broken skills on level 5(like the IP recovery ones or the chants). 


But to ask again, I'm not sure if you missed those points: 
The "Damage(?)" value in enemy moves: May that be kind of the mag/str the damage is calculated with, as enemies have no natural mag/str but this additional damage stat? I'll try to test for that myself, but just wanted to ask if you have already gone through that. Seems like you at least know that value affects damage. 

And on the "special" property again: Is it somehow feasable to modify what exactly they do? Like which skills Magica Esoterica affects, or how strong the taunt on Decoy is? It seems like it might be somehow hard-coded, but I hope not.

**Comment by krogenth** [comment]
I went ahead and added support for the Levelup data, hopefully the structure is alright. The download can be found here: https://github.com/krogenth/G2DataGUI/releases/tag/0.0.10b

As for the remaining questions:
1. for the enemy groups, there's a lot of information you need to know to edit it all, but in general the following is important:
    * you will need this file, specifically the line numbers are the index, called `Enemy Index` in the `MDT`'s `Enemy Groups` section: https://github.com/krogenth/G2DataGUI/blob/master/docs/nme%20list.txt
    * for the positions of enemies, this can be found under the `MDT`'s `Enemy Positions` section, giving x & z coordinates for their bounding box(where they can travel).
2. for critical hits, there's not much that's known that can be changed, aside from how much SP is regenerated from the attack. There might be another value in the `PC_INIT` section that modifies critical hit statistics, but I am not aware of them.
3. I believe I did end up testing the `Damage (?)`value and finding that it did change the damage dealt, but would recommend testing it.
4. As far as I am aware, all special effects are hard-coded, but there might be a file that expresses them somewhere as well.

**Comment by VaylenObscuras** [comment]
Oh, that was quick. Thanks a lot. Structure seems perfectly fine. But man, it's a bit of a drag that you need to edit every single level.  But at least I have something to work with. Now, once I get the hardmode toggle I'll start to modify enemies. Ive been starting a playthrough on hard already and jotted down some notes for enemy changes already. 

Hm, I don't quite get the values for "Enemy Index". I've looked through groups in Garmia tower floor 1&3 and the enemy Index value is always 0 or 1, which doesn't make sense to me. 

Regarding enemies, I noticed that there are different... AI presets, with different skill-use chances and all that. How can I find out and edit which enemies use which AI preset? For example, the Gargoyles in Garmia Tower likely have a different AI than the ones in Lilligue cave. 

Regarding Criticals and PC_Init.. There is a line for IP Stun/IP Cancel Stun, but I am not sure what it is used for. The value is very low(15/30). Any idea what those are for? 

Would be great to find a file that expresses all the special stuff. Maybe you'll find some ways to alter them.. Cause as it is, there are a few too many special effects that just kind of.. break the game if you abuse them.

**Comment by krogenth** [comment]
Sorry, that's my bad, `Enemy Index` was wrong, it's `Enemy Offset` that you need to reference that file for.

AI presets are all there in the `ENEMY AI` section, there's different AIs, and you would want the `AI Type` value to mess with. These are hard-coded as well, and I haven't dug into them at all, but it handles when that specific AI set is used. For example, one of the ghouls are an AI specific to increase the chance to use the drain ability to regenerate health when it's at 50% or lower HP.

The `IP Stun`/`IP Cancel Stun` are for resistances in `PC_INIT` for when that character is hit. You can hover your mouse over some of the labels to things to see a bit more information about it as well, like the `T_` labels in `PC_INIT`.

**Comment by VaylenObscuras** [comment]
Okay. So enemy offset defines which enemy it is. How are groups of multiple different enemies defined? You oftentimes see groups of multiple enemies walking around together. 

Hm.. I really need some more information about AI Type then. It's kinda important to know when a different AI is used, even if I cannot precisely edit that. I think there is a lot of potential for more interesting enemy design if I had that at my disposal. 

Ahh, whoops. I noticed the hover functionality, but kinda forgot it was there for that line.

**Comment by krogenth** [comment]
Sorry it took a while, but there's a good amount of stuff that I should update you about...The release can be found here: https://github.com/krogenth/G2DataGUI/releases/tag/0.0.12b

1. I have added support for toggling between `Normal Mode` and `Hard Mode` for enemies/bosses
    * It can be found under the `File` dropdown as either `Read Hard Mode` or `Read Normal Mode` depending on which one is currently read in
3. Enemies and bosses have been separated to different sections due to some future work that will need to be done
4. The majority of data on enemies is editable, but there is some missing information for bosses(mainly different move sets)

Now for the questions you had asked:

1. AI is a bunch of hard coded information that I just have not had the time to dig into. I know there are some things some enemies use, but that's about it
2. The `Export All to CSV` is just to generate a bunch of CSV files of the data currently loaded into the program, they can be found in the `.csv/` directory
3. To start a new game with whatever data you entered/modified, you just need to save the data, then launch Grandia 2, then start a new game(if required for the data change)
4. I can look into adding buttons or the like to skip through the levelup list, or hotkeys
5. Levelup stats can be seen here: https://github.com/krogenth/G2DataGUI/blob/master/docs/TB_LVUP.CSV
    * If you want to see the cumulative stats, that can technically be done too

**Comment by VaylenObscuras** [comment]
Oh, very nice. That was quick of you, thanks. 
One suggestion, though: I think that the seperate windows(like for enemy moves and ai) in the program actually made editing a bit easier, cause you could just place any currently relevant windows where you need them at the moment. With the drop down, some windows get really large and I need to scroll down, which actually makes it a bit more cumbersome, imo. 


Hm, okay. I won't mess too much with AI then if I cannot tell what it will do. Would be really helpful if you could dig a bit into it in the future. 

Ah no, I did not mean new game in that sense, but on a fresh install. Basically: How to save the mod and install it onto a fresh file. I'd just probably copy the whole data-folder, but I think there might be a more elegant solution. 

Buttons or hotkeys would really help with making the editing of level-ups a little bit faster. It would also help if you could edit "Roan" and "Prince Roan" at the same time - at least having the option cuts out a lot of work. 
Thanks for that list, I'll definitely put that to good use. 
I've already gone a good bit through the levelup lists and one thing that struck me as quite odd is how low the stat growth on Magic and Mentality is, even for the more mage~y characters. Any idea why that might be? Assuming that "Power" in moves/magic is likely the scaling, it doesn't seem like Magic has a particulary higher scaling than physical moves - it's a little bit higher across the board, but not by much. Heals do have very high mentality scaling in the base game, though.

**Comment by krogenth** [comment]
1. That's a fair suggestion, I just kind of go based on my own screen resolution
2. The hard-coded parts exist already, so if you want to try and deduce what each value means, go for it, I will try to get around to determining those values and what they do, but I wouldn't wait for it
3. Ok, that makes more sense. In that case, you would need to copy the `./content/` or `./afs/` directory depending on version you are using(HD vs Anniversary), multiple files aren't fully fleshed out, particularly the map files
4. I don't really know why off the top of my head, but likely that it was balanced in other ways

**Comment by VaylenObscuras** [comment]
I'll certainly try to deduce what some values for the AI mean. 
But there is a certain AI "condition" I am particulary interested in: Changing behaviour based on Status. At its simplest, this would just be something like de-prioritizing move/magic and prioritizing the other when affected by move or magic block. 

Okay, thanks. 

Hmm.. I'll take a look at the stats of each character and just go with my gut. If I document everything properly, it should be easy enough to make some changes if anything is out of line. I believe I remember magic being generally a weaker than moves later into the game, except a few very high tier magics.

**Comment by VaylenObscuras** [comment]
I think I noticed a mistake regarding levelups while making some spreadsheets. 
The stats for Magic/Mentality and Agi/Speed are flipped, both in the list you gave me and in the program itself. 
MOV is actually Mag, ACT is actually Men and vice versa.

**Comment by krogenth** [comment]
They are indeed flipped, just double checking that everything is in the right place and will put out a fix for it.

**Comment by VaylenObscuras** [comment]
Thanks. Good thing I didn't actually start modding levelups extensively yet, would have been quite a hassle.

**Comment by VaylenObscuras** [comment]
Okay, thank you. 
Really, you cannot tell how glad I am that I caught this before going through all the editing lol.

**Comment by VaylenObscuras** [comment]
Okay, after literal hours of work, I've finally edited the base stats and stat growth of all characters x.x That was quite a lot of work. 

Please keep me updated on any new updates to the program or if you have any new information for me. I'd still like to know a bit more about AI and "Special" thingies ^.^

**Comment by VaylenObscuras** [comment]
Just noticed something while editing enemies and their status resists: Clicking on any of the status resist boxes ticks or unticks ALL of them. I cannot, for example, make an enemy resist everything but paralysis. Seems like a bug to me?

**Comment by VaylenObscuras** [comment]
Figured as much ^.^ 

No worries, things take time. I'm just glad for any new options.

**Comment by krogenth** [comment]
A fix for the ailments can be found here: https://github.com/krogenth/G2DataGUI/releases/tag/0.0.14b

**Comment by VaylenObscuras** [comment]
Thanks ^.^

**Comment by VaylenObscuras** [comment]
Just to doublecheck, did the erroneous statuses actually change anything? I fear that the bug might have fucked up something.

**Comment by krogenth** [comment]
It was essentially pointing to some incorrect data, so if you attempted to modify it, yes, it will now be wrong.

**Comment by VaylenObscuras** [comment]
I did attempt to modify some things. Just checked and there doesn't seem to be anything out of the ordinary. I hope that means everything's alright..?

**Comment by krogenth** [comment]
Everything should be fine then, it was only pointing to the wrong ailments settings(in one way or another), so long as they look fine, it will be all good.

**Comment by VaylenObscuras** [comment]
Okay, that's reassuring. 

So, after a week of work, I can finally actually play the game xD

**Comment by VaylenObscuras** [comment]
I just noticed~ It seems like Act and Move in the levelup editor are switched.

**Comment by VaylenObscuras** [comment]
Quick question: What is that value in enemy moves called "Ailments Bitflag"? 
I assume it's some value that associate ailments, as it changes when I tick stuff on or off.. But it also seems to be a bit buggy. For example: On an attack with no ailments, ticking poison on causes the value to go to "1", clicking it again(so ticking it off), it stays at 1... and ticking it once again it goes down to 0(poison should once again be ticked ON at this point). Seems a bit buggy, but I didnt get to test it so far.

**Comment by krogenth** [comment]
Sorry I haven't responded in a while, I was juggling a few different things at the same time. I have worked on some things, primarily allowing users to more easily adjust some labels(egg names, animation names, etc.), along with fixing several issues with the ailment bitflags(initial load failing, switching moves or boss/enemy causing the checkboxes to mess up, etc.).

The fixes themselves can be viewed here: #22 
Once I verify a few more things, I'll be merging and releasing this.

**Comment by krogenth** [comment]
The new release can be found here: https://github.com/krogenth/G2DataGUI/releases/tag/0.0.15b

There is now a new file, `definitions.json`, which you can edit yourself if you so choose, just keep it in the same directory as the program.

**Comment by VaylenObscuras** [comment]
I ran into a problem. I wanted to add some spells to an enemy(Giant Mantis, in Baked Plains). 
The enemy doesn't have any moves or spells usually. Edited the AI for that in and when they attempt to use the spell, they just do.. nothing, standing there. As if locked into an animation that doesn't exist. The battle also cannot continue, as it seems to wait for the spell to be finished.. which it never will be, so it seems. 
I assume that, cause they have no spellcasting animation or anything, this happens. Any idea how to get around that?

**Comment by VaylenObscuras** [comment]
And another thing. 
As you can guess, Im currently at the baked plains. Dodos are still enemies there which are.. basically just a waste of time. They are  too weak but I cant exactly buff them without fucking over the early game. 
So I'm thinking of replacing them for a new enemy. Maybe just a stronger version of the Dodo. What exactly would go into creating a new enemy and inserting them instead of the Dodos in Baked Plains?

**Comment by krogenth** [comment]
1. Sorry, yes, the `ACT` and `MOV` values should be correct now.
2. There is a value that I need to add a label for(currently labelled `Unknown #2`) for enemy/boss moves, this basically indicates if the move is a normal attack, or a move/spell. most likely this is the cause, but there might be other things too. If desired, we can work through you giving me the necessary file to check for you.
3. Adding/removing/changing enemies in areas is very difficult, it's a problem I have been trying to work on off and on for a while unfortunately. Not impossible, just a ton of work.

**Comment by VaylenObscuras** [comment]
Regarding the second point, what would the necessary file be? 
I did manage to get the Giant Mantis encounter "right", I feel. But the ability to add additional spells and moves would surely be helpful. 

Hmm.. Well, I'll guess there'll be a few low level dodos flying around baked plains then. If I recall correctly, that sort of thing isnt a re-occuring problem.

**Comment by krogenth** [comment]
That entirely depends on the enemy.
You can view this listing to see what file corresponds to what enemy(the `dxx` is the file prefix): https://github.com/krogenth/G2DataGUI/blob/master/docs/nme%20list.txt

You want the file ending with `_0.dat` to share.

**Comment by VaylenObscuras** [comment]
Okay, I found the right file for Giant Mantis. 
How can I share the file? Tried just dragging it here, but it says that the file type isnt supported.

**Comment by krogenth** [comment]
You can just right click and zip the file and upload it that way.

**Comment by VaylenObscuras** [comment]
Okay, I'll do that soon. 

Im currently wanting to edit Valmars tongue but some numbers seem a little.. off. When reading normal mode, both first and second encounter of the tongue and its parts have the same health. Switching to hard mode, the health values of the parts of the tongue seem appropriate for first encounter, but the second encounter doesnt have more health. As its kinda difficult to find information about what the proper hardmode encounter should have in terms of stats, I cannot really double-check this. But something is definitely wrong. Would appreciate it if you could look into that.

**Comment by VaylenObscuras** [comment]
Okay, that bug seems to be fixed. 
However, there are still various oddities with the properties of the skills. For example, Freeze! from Valmars tongue being listed as Target Type: Enemy Line, or Burnflame from the Head being All Targets.

**Comment by krogenth** [comment]
I will have to look into them, I believe all information should be 1-to-1 against the character move information.

**Comment by krogenth** [comment]
Figured it out, the `Target Effect` was being used in place of the `Target Type`, fix can be found here: https://github.com/krogenth/G2DataGUI/releases/tag/0.0.17b

**Comment by VaylenObscuras** [comment]
Okay, the patch worked. Thanks. 
Next issue with bosses was.. The Boss AI. It reads "0" on everything - AI type and all moves, on all AI Indexes. Seems to be like that for all bosses.

**Comment by krogenth** [comment]
Yup, sorry, looks like I forgot to add reading in the boss AI data, so if you've saved at all, you'll want to reverify files to get back the original data. The update can be found here: https://github.com/krogenth/G2DataGUI/releases/tag/0.0.18b

**Comment by krogenth** [comment]
The issue is this:
1. The base move information displayed is only a part of the information for boss moves. If you look at the AI part, the chance for `Starving Tongue` is 0%, meaning it can't even be used for that specific moveset.
2. There is a completely different file full of different movesets, but do not give different AI to go along with them, and there is no clear definition how how/when these movesets are loaded/used.

I'll try looking into it some more.
