### ISSUE TITLE
Investigate possible GUI libraries

### ISSUE THREAD

**Issue by krogenth** [krogenth/G2DataGUI#6]
While ImGui is quick to setup, it is not quite as user-friendly as desired. Therefore, investigation of possible GUI libraries that can be used in place of ImGui to provide a more user friendly layout is required.

Possible leads would include:
* [wxWidgets](https://www.wxwidgets.org/)
* [QT](https://www.qt.io/)
* [FLTK](https://www.fltk.org/)
* [Boost::UI](https://kosenko.github.io/boost.ui/)

Other possibilities can be found here: https://old.reddit.com/r/cpp/comments/babfl5/a_pretty_big_list_of_c_gui_libraries/
Ideally we would want standard library conforming, with minimal code requirements so it's easier for others to pick up work.

**Comment by Guernouille** [comment]
I have a bit of experience with Qt 5, but I didn't work with it for more than 3 years, and I didn't follow any tutorial so I don't know the good practices with it. I may still be able to help though :q

**Comment by krogenth** [comment]
After looking into some of the available libraries, I am slightly interested in [sciter](https://sciter.com/) and [ultralight](https://ultralig.ht/). Both would allow for using html/css/js for rendering the ui, which would be very flexible for design decisions. However, the dependencies(at least sciter) are a bit bloated, and may not be the easiest in terms of compiling.

**Comment by krogenth** [comment]
After looking through the ultralight documentation and samples, I'm removing that from the list of potential frameworks.

**Comment by krogenth** [comment]
It took a while, but after looking through and trying some example code from a variety of GUI libraries and frameworks, I think, Qt will end up being the best possible option for this. I'd prefer targeting the latest version, but if it's quicker to get an older version to get moving, that's where things can start. The only slight concern I can see if the issue of names/descriptions being fixed length strings, but hopefully that won't be too difficult to handle.
